import axios, { AxiosPromise, AxiosRequestConfig, AxiosResponse } from "axios";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Checkbox from "../components/checkbox";

interface Prefectures {
  props: {
    message: null;
    result: {
      prefCode: number;
      prefName: string;
    }[];
  };
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await axios.get(
    "https://opendata.resas-portal.go.jp/api/v1/prefectures",
    {
      headers: { "X-API-KEY": `${process.env.NEXT_PUBLIC_RESAS_API_KEY}` },
    }
  );

  const props = response.data;

  return {
    props: { props },
  };
};

const Home = ({ props }: Prefectures) => {
  const [prefPopulation, setPrefPopulation] = useState<
    { prefName: string; data: { year: number; value: number }[] }[]
  >([]);

  const handleClickCheck = (
    prefName: string,
    prefCode: number,
    check: boolean
  ) => {};

  return (
    <div className="container mx-auto">
      <Head>
        <title>Prefectures graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-6">
        都道府県
        <Checkbox prefectures={props.result} onChange={handleClickCheck} />
      </div>
    </div>
  );
};

export default Home;
