import axios from "axios";
import type { GetStaticProps } from "next";
import Head from "next/head";
import { useState } from "react";
import Checkbox from "../components/checkbox";
import Graph from "../components/graph";

interface Prefectures {
  props: {
    message: null;
    result: {
      prefCode: number;
      prefName: string;
    }[];
  };
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await axios.get(
    "https://opendata.resas-portal.go.jp/api/v1/prefectures",
    {
      headers: { "X-API-KEY": `${process.env.NEXT_PUBLIC_RESAS_API_KEY}` },
    }
  );

  const props = response.data;

  return {
    props: { props },
  };
};

const Home = ({ props }: Prefectures) => {
  const [prefPopulation, setPrefPopulation] = useState<
    { prefName: string; data: { year: number; value: number }[] }[]
  >([]);

  const handleClickCheck = (
    prefName: string,
    prefCode: number,
    check: boolean
  ) => {
    console.log(prefName + prefCode + check);
    let prefPopulationByCheck = prefPopulation.slice();

    if (check) {
      axios
        .get(
          "https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear?prefCode=" +
            String(prefCode),
          {
            headers: {
              "X-API-KEY": `${process.env.NEXT_PUBLIC_RESAS_API_KEY}`,
            },
          }
        )
        .then((results) => {
          prefPopulationByCheck.push({
            prefName: prefName,
            data: results.data.result.data[0].data,
          });

          setPrefPopulation(prefPopulationByCheck);
        })
        .catch((error) => {
          return;
        });
    } else {
      const deleteIndex = prefPopulationByCheck.findIndex(
        (value) => prefName === value.prefName
      );

      if (deleteIndex === -1) return;
      prefPopulationByCheck.splice(deleteIndex, 1);
      setPrefPopulation(prefPopulationByCheck);
    }
  };

  return (
    <div className="container mx-auto">
      <Head>
        <title>Prefectures graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center xl:text-left bg-slate-200">
        <h1 className="text-xl py-2">都道府県別の総人口推移グラフ</h1>
      </div>
      <div className="py-6">
        <h2 className="pl-2 pb-4 xl:pl-0">都道府県</h2>
        <Checkbox prefectures={props.result} onChange={handleClickCheck} />
      </div>
      <div>
        <Graph populationdata={prefPopulation} />
      </div>
    </div>
  );
};

export default Home;
